### PR TITLE
add test instructions to readme

### PR DESCRIPTION
**Pull request by haydennyyy**
I had to go to your Discord server to find out how to test this.

While that could be chalked up to me being a Python noob, I think it could be useful to explain how to run unit tests on this. So I added instructions to the README.

### CODE REVIEW

**Comment by asottile** [comment]
this is ~fairly standard for python projects so I'm not sure I want to document it here -- I do for `pre-commit` in a `CONTRIBUTING.md` but that's a big/popular project 🤔

**Comment by haydennyyy** [comment]
Alright, fair enough. Just thinking about the noobs like myself. If you don't want it shipped, I'll just close the PR. :)

**Comment by asottile** [comment]
yeah sg, if this gets wildly popular I'll let you set up a `CONTRIBUTING.md` ;)

**Comment by haydennyyy** [comment]
I've never written one of those lmao

**Pull request closed without merging**
