### PR TITLE
Change Syntax Highlightert on save with known extension.

### PR DESCRIPTION
**Pull request by Marsma13**
I am using babi in different way than you usually starting from babi. When I save file the syntax highliting is not enabled and i have to close and reopen file. I added simple setter on filename to initialize syntax highlighter. Hope I do not mess with tests :)

### CODE REVIEW

**Comment by asottile** [comment]
this doesn't really solve the issue outlined in #82 only a subset of it

**Comment by asottile** [comment]
note that you can use `:reload` today without needing to close and reopen

**Comment by Marsma13** [comment]
For me :reload does not work. That is why I came with that patch.

**Comment by asottile** [comment]
err sorry, I meant `:retheme`

**Pull request closed without merging**
