### PR TITLE
fix Alt-UP crash if first line empty

### LINKED ISSUE #218: Alt-UP crashes if the first line in the buffer is empty
To reproduce:
- open babi
- press enter
- press Alt-UP

This happens because there is no bound check in Alt-UP action implementation when counting the offset.

I can issue a pull request with slightly different implementation where the bound check is obvious. If you would like to keep the current code it suffices to add two more if statements.

### PR DESCRIPTION
**Pull request by gryzus24**
fixes #218

### CODE REVIEW

**Comment by asottile** [comment]
this fix is fairly invasive (essentially a rewrite) -- is there a simpler change that can be done?  also this will need a test to demonstrate the breakage -- you can find examples in tests/features/movement_test.py

**Comment by gryzus24** [comment]
Yes, we can just add:
```python
if self.buf.y < 0:
    self.buf.y = 0
```
after every assignment to `self.buf.y`.
Sorry for being too invasive, I just find this implementation slightly more readable.
Also I'm not sure how to write a test for this, because for some reason they fail on my machine:
`FAILED tests/features/movement_test.py::test_indentation_using_tabs[tmux] - AssertionError: Timeout ...`
`...`
`44 failed, 586 passed`
I have tmux installed. Not sure what causes it.

**Comment by ClasherKasten** [comment]
For me changing the first while-loop to
```
while (
    self.buf[self.buf.y - offset] == '' and
    self.buf.y - offset - 1 >= 0
):
```
worked too.
I ran coverage and it says 100%.

**Comment by asottile** [comment]
@gryzus24 I ended up adding you as a co-author on #220 

@ClasherKasten in the future it's bad form to attempt a patch while another is in progress -- it's better to work collaboratively instead!

**Pull request closed without merging**
