### PR TITLE
Fixing issues #180 and #183

### PR DESCRIPTION
**Pull request by ClasherKasten**
Revert "Revert "Merge pull request #181 from ClasherKasten/feature/issue-180""
This reverts commit c4853f26e433f61493ee4e68de9eb3f10fc8f47e.

Tried to clean up git a second time.

I just did like you mentioned in my last PR, but to name my branch the same i had to delete the `origin/issues_180_and_183` branch and create it new. I don't know if this would be unnecessary.

### CODE REVIEW

**Comment by asottile** [comment]
ah you could have force-pushed to the old branch name

also this should be two commits -- one that's just the clean revert, and then a second for your new changes on top of that

**Comment by ClasherKasten** [comment]
Hope it is no problem that i reverted the version manually, I really don't know why the version changed to 0.0.26 before in the last PR.

**Comment by asottile** [comment]
you shouldn't need to touch the version -- 0.0.26 is the correct one on the main branch

**Comment by asottile** [comment]
bleh, I just fixed it for you

**Review by asottile — APPROVED** [review]

**Pull request merged**
