### PR TITLE
Handle errors when replacing

### LINKED ISSUE #46: regex replace invalid replace causes crash
```
$ nano babi/file.py 
Traceback (most recent call last):
  File "/home/asottile/bin/nano", line 8, in <module>
    sys.exit(main())
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/main.py", line 108, in main
    return c_main(stdscr, args, stdin)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/main.py", line 50, in c_main
    res = _edit(screen, stdin)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/main.py", line 30, in _edit
    ret = Screen.DISPATCH[key.keyname](screen)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/screen.py", line 383, in replace
    self.file.replace(self, search_response, response)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/file.py", line 142, in clear_selection_inner
    ret = func(self, *args, **kwargs)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/file.py", line 465, in replace
    replaced = match.expand(replace)
  File "/home/asottile/opt/venv/lib/python3.6/re.py", line 321, in _expand
    template = sre_parse.parse_template(template, pattern)
  File "/home/asottile/opt/venv/lib/python3.6/sre_parse.py", line 895, in parse_template
    this = sget()
  File "/home/asottile/opt/venv/lib/python3.6/sre_parse.py", line 255, in get
    self.__next()
  File "/home/asottile/opt/venv/lib/python3.6/sre_parse.py", line 245, in __next
    self.string, len(self.string) - 1) from None
sre_constants.error: bad escape (end of pattern) at position 24
```

for example, try a replace with a trailing backslash

### PR DESCRIPTION
**Pull request by AndrewLaneX**
Closes #46

### CODE REVIEW

**Comment by asottile** [comment]
I think ideally the strings would be validated up front instead of at the replacement time if possible -- that way a more direct error message can be given "invalid replacement string" or "invalid regex" or some such instead of just "replacement failed" without an explanation

**Comment by AndrewLaneX** [comment]
Is there a way to validate it? If not, the regex is already validated so maybe "invalid replacement" would just work?

**Comment by asottile** [comment]
> Is there a way to validate it? If not, the regex is already validated so maybe "invalid replacement" would just work?

I'm not sure -- there probably is.  the ideal user experience is to let them know before they start searching around and replacing though -- so ideally it would catch it immediately after putting in the replacement string 😢

**Review by asottile — APPROVED** [review]

**Pull request merged**
